; A071026: Triangle read by rows giving successive states of cellular automaton generated by "Rule 188".
; Submitted by Simon Strandgaard
; 1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1

lpb $0
  add $1,1
  sub $0,$1
lpe
add $1,$0
bin $1,3
mod $1,-2
sub $1,1
bin $1,$0
mov $0,$1
add $0,2
mod $0,2
