; A071023: Triangle read by rows giving successive states of cellular automaton generated by "Rule 78".
; Submitted by Simon Strandgaard
; 1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1

lpb $0
  add $1,1
  sub $0,$1
lpe
add $1,$0
div $0,2
add $0,1
mod $1,2
gcd $1,$0
bin $1,$0
mov $0,$1
