; A071023: Triangle read by rows giving successive states of cellular automaton generated by "Rule 78".
; Submitted by Simon Strandgaard
; 1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1

lpb $0
  add $1,1
  sub $0,$1
lpe
pow $0,5
trn $0,$1
add $0,1
mod $0,2
