; A183543: Second of two complementary trees generated by the Wythoff sequences.
; Submitted by Simon Strandgaard
; 3,6,11,10,18,19,32,17,29,30,50,31,52,53,87,28,47,48,79,49,81,82,134,51,84,85,139,86,141,142,231,46,76,77,126,78,128,129,210,80,131,132,215,133,217,218,354,83,136,137,223,138,225,226,367,140,228,229,372,230,374,375,608
; Formula: a(n) = A048680(A004755(n))-1

mov $3,-1
add $0,1
lpb $0
  mov $2,$0
  mul $2,6
  mod $2,4
  add $2,2
  mul $2,$3
  div $4,-1
  sub $4,$3
  sub $0,2
  dif $0,2
  add $0,1
  sub $1,$2
  sub $3,$4
lpe
mov $0,$1
div $0,2
add $0,1
