; A217990: Size of largest semigroup generated by one Boolean n X n matrix.
; Submitted by Simon Strandgaard
; 1,2,5,10,17,26,37,50,65,82,101,122,145,170,197,226,257,290,420,840,401,442,840,3360,1680,626,677,1512,10080,15120,901,962,2520,25200,75600,30240,1297,1370,3960,55440,277200,332640,1765,1850,5940,110880,831600,1995840,665280,2402,2501,8580,205920,2162160,8648640,8648640,3137,3250,12012,360360

mov $1,$0
pow $1,2
add $1,1
seq $0,59344 ; Triangle read by rows: row n consists of the nonzero coefficients of the expansion of 2^n x^n in terms of Hermite polynomials with decreasing subscripts.
max $0,$1
