; A070909: Triangle read by rows giving successive states of cellular automaton generated by "Rule 28" and by "Rule 156".
; Submitted by Simon Strandgaard
; 1,1,1,1,0,1,1,0,1,1,1,0,1,0,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0

sub $0,1
lpb $0
  add $1,1
  sub $0,$1
lpe
sub $1,$0
trn $1,1
pow $0,$1
mod $0,2
