; A039745: Diameter of symmetric group S_n when generated by (1,2) and (1,2,3,...,n).
; Submitted by Simon Strandgaard
; 0,1,2,6,11,18,25,35,45,58,71,87,103

pow $0,2
mov $1,$0
seq $1,308358 ; Beatty sequence for sqrt(3)/4.
add $0,1
div $0,2
mul $0,2
add $0,$1
div $0,2
