; A353084: Column 0 of the extended Trithoff (tribonacci) array.
; Submitted by Simon Strandgaard
; 1,2,3,5,6,7,8,9,10,12,13,14,15,16,18,19,20,21,22,23,25,26,27,29,30,31,32,33,34,36,37,38,39,40,42,43,44,45,46,47,49,50,51,52,53,54,56,57,58,59,60,62,63,64,65,66,67,69,70,71,73,74,75,76,77,78,80

mov $2,$0
pow $2,2
lpb $2
  mov $3,$1
  seq $3,3146 ; Positions of letter c in the tribonacci word abacabaabacababac... generated by a->ab, b->ac, c->a (cf. A092782).
  sub $3,1
  add $0,1
  add $1,1
  add $2,$3
  sub $2,$0
lpe
add $0,1
