; A231874: Elements of the segmented integer compositions sub-operad SComp of TN_3 generated by 00, 01, 02.
; Submitted by Simon Strandgaard
; 1,11,12,13,111,112,113,121,122,123,131,132,133,1111,1112,1113,1121,1122,1123,1131,1132,1133,1211,1212,1213,1221,1222,1223,1231,1232,1233,1311,1312,1313,1321,1322,1323,1331,1332,1333

mov $2,1
lpb $0
  sub $0,1
  mov $3,$0
  mod $3,3
  mul $3,$2
  div $0,3
  add $1,$3
  mul $2,10
lpe
mul $2,10
add $0,$2
div $0,9
add $0,$1
