; A138017: Sequence generated by incidence matrix of the Fano plane, PG(2,2).
; Submitted by Simon Strandgaard
; 1,3,5,15,37,111,317,951,2821,8463,25325,75975,227797,683391,2049917,6149751,18448741,55346223

mov $1,1
mov $2,1
mov $3,1
lpb $0
  sub $0,1
  mov $4,$1
  mul $4,2
  add $4,$2
  mov $1,$3
  mul $2,3
  mov $3,$4
lpe
mov $0,$3
