; A082848: Duplicate of A078588.
; Submitted by Simon Strandgaard
; 0,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0,1,1,0,1,0

mul $0,2
seq $0,99267 ; Numbers generated by the golden sieve.
mod $0,2
