; A082507: Generated by a 3rd-order formal recursion with suitable initial values as follows: a(n) = n - a(n-1) - a(n-2) - a(n-3); a(0)=a(1)=a(2)=0.
; Submitted by Simon Strandgaard
; 2,0,0,0,3,1,1,1,4,2,2,2,5,3,3,3,6,4,4,4,7,5,5,5,8,6,6,6,9,7,7,7,10,8,8,8,11,9,9,9,12,10,10,10

mov $1,$0
gcd $1,4
div $1,3
mul $1,2
div $0,4
add $0,$1
