; A105392: Frobenius number of the subsemigroup of the natural numbers generated by successive pairs of Lucas numbers.
; Submitted by Simon Strandgaard
; 0,5,17,59,169,475,1287,3449,9149,24155,63557,166919,437839,1147645,3006777,7875419,20623889,54003395,141397847,370208849,969258949,2537616955,6643671117,17393524559,45537109919,119218140725

mov $1,1
lpb $0
  sub $0,1
  add $2,2
  mov $3,$1
  mov $1,$2
  add $2,$3
lpe
mul $3,$1
add $3,$2
mov $0,$3
