; A181653: Generalized (conditional) Riordan array with k-th column generated by x^k*(1+x) if k mod 2 = 0, x^k*(1+x+x^2) otherwise.
; Submitted by Simon Strandgaard
; 1,1,1,0,1,1,0,1,1,1,0,0,0,1,1,0,0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,1

mov $1,1
lpb $0
  add $1,1
  sub $0,$1
lpe
sub $1,$0
pow $1,5
add $1,1
gcd $0,$1
div $0,$1
