; A181653: Generalized (conditional) Riordan array with k-th column generated by x^k*(1+x) if k mod 2 = 0, x^k*(1+x+x^2) otherwise.
; Submitted by Simon Strandgaard
; 1,1,1,0,1,1,0,1,1,1,0,0,0,1,1,0,0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,1

lpb $0
  add $2,1
  sub $0,$2
lpe
mov $1,$0
div $1,2
sub $0,$2
add $2,1
div $2,2
sub $2,$1
add $0,$2
bin $2,$0
mov $0,$2
