; A267594: Triangle read by rows giving successive states of cellular automaton generated by "Rule 173" initiated with a single ON (black) cell.
; Submitted by Ralfy
; 1,0,1,0,0,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

mov $1,$0
add $0,2
mov $2,$0
mov $0,$1
lpb $2
  mod $2,6
  seq $0,10052 ; Characteristic function of squares: a(n) = 1 if n is a square, otherwise 0.
lpe
mul $1,2
bin $1,2
mov $2,$0
sub $2,1
bin $2,$1
min $1,1
add $2,$1
mov $0,$2
mod $0,2
