; A127248: Triangle whose k-th column is generated by (1-A010060(1+k)*x)*x^k.
; Submitted by Simon Strandgaard
; 1,-1,1,0,-1,1,0,0,0,1,0,0,0,-1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,-1,1,0,0,0,0,0,0,0,-1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1

mov $1,$0
seq $1,127243 ; Triangle whose k-th column is generated by (1+A010060(1+k)x)*x^k.
seq $0,257075 ; a(n) = (-1)^(n mod 3).
mul $0,$1
